msg: "Git - DEV Environment - Hello Common BFF."
service:
  name: gemini-common-bff
  version: 1.0.1-DEV
logstash:
  host: localhost
  port: '5044'
server:
  port: '8081'
management:
  endpoints:
    web:
      exposure:
        include:
          - prometheus
app:
  token-exchange-client-id: spring_keycloak_demo_client_2
  token-endpoint: "http://localhost:8080/auth/realms/demo/protocol/openid-connect/token"
  client-secret: 9ee1dcb4-4983-4ee5-b8a2-ae384f6fc4e4
  client-secret-2: 9ee1dcb4-4983-4ee5-b8a2-ae384f6fc4e4
  client-id: spring_keycloak_demo_client
spring:
  security:
    oauth2:
      client:
        registration:
          client-id:
            client-id: spring_keycloak_demo_client_3
            client-secret: 9ee1dcb4-4983-4ee5-b8a2-ae384f6fc4e3
            authorization-grant-type: client_credentials
        provider:
          client-id:
            issuer-uri: http://localhost:8080/auth/realms/demo
            token-uri: http://localhost:8080/auth/realms/demo/protocol/openid-connect/token